---
# tasks file for semaphore-repo-pod

- name: Update the Netos Pod repository
  become: yes
  git:
    repo: "{{ NETOS_POD_GIT }}"
    dest: /netos/netos-pod
    force: yes
    update: yes
  register: git_output

- name: Find all bash scripts in the netos-pod directory
  find:
    paths: /netos/netos-pod/scripts/bash
    patterns: "*.sh"
  register: bash_scripts

- name: Ensure all bash scripts are executable
  file:
    path: "{{ item.path }}"
    mode: '0755'
  loop: "{{ bash_scripts.files }}"